In [8]:
# Getting Started with Pandas
# Objective: Introduce students to using Pandas for data analysis by loading data into Pandas
# DataFrames.

# Question 1: Importing Pandas and Loading a CSV File
# 1. Open your Jupyter Notebook or a Python environment.
# 2. Import the pandas library.
# 3. Load a CSV file into a DataFrame.

import pandas as pd 

df = pd.read_csv('/workspaces/AI_DATA_ANALYSIS_/src/student_habits_performance.csv')










# Question 2: Displaying the First Few Rows
# 4. Use the head() method to display the first five rows of the DataFrame.


print(df.head())


# Question 3: Basic Data Information
# 5. Use the info() method to get a concise summary of the DataFrame.

df.info()

  student_id  age  gender  study_hours_per_day  social_media_hours  \
0      S1000   23  Female                  0.0                 1.2
1      S1001   20  Female                  6.9                 2.8
2      S1002   21    Male                  1.4                 3.1
3      S1003   23  Female                  1.0                 3.9
4      S1004   19  Female                  5.0                 4.4

   netflix_hours part_time_job  attendance_percentage  sleep_hours  \
0            1.1            No                   85.0          8.0
1            2.3            No                   97.3          4.6
2            1.3            No                   94.8          8.0
3            1.0            No                   71.0          9.2
4            0.5            No                   90.9          4.9

  diet_quality  exercise_frequency parental_education_level internet_quality  \
0         Fair                   6                   Master          Average
1         Good                   6              High School          Average
2         Poor                   1              High School             Poor
3         Poor                   4                   Master             Good
4         Fair                   3                   Master             Good

   mental_health_rating extracurricular_participation  exam_score
0                     8                           Yes        56.2
1                     8                            No       100.0
2                     1                            No        34.3
3                     1                           Yes        26.8
4                     1                            No        66.4
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     1000 non-null   object
 1   age                            1000 non-null   int64
 2   gender                         1000 non-null   object
 3   study_hours_per_day            1000 non-null   float64
 4   social_media_hours             1000 non-null   float64
 5   netflix_hours                  1000 non-null   float64
 6   part_time_job                  1000 non-null   object
 7   attendance_percentage          1000 non-null   float64
 8   sleep_hours                    1000 non-null   float64
 9   diet_quality                   1000 non-null   object
 10  exercise_frequency             1000 non-null   int64
 11  parental_education_level       909 non-null    object
 12  internet_quality               1000 non-null   object
 13  mental_health_rating           1000 non-null   int64
 14  extracurricular_participation  1000 non-null   object
 15  exam_score                     1000 non-null   float64
dtypes: float64(6), int64(3), object(7)
memory usage: 125.1+ KB

In [11]:
# Data Inspection & Selection
# Objective: Learn how to inspect data and select specific data points.

# Question 1: Inspecting Column Data Types
# 6. Use the dtypes attribute to inspect the data types of each column.

print(df.dtypes)


# Question 2: Selecting Columns
# 7. Select a single column from the DataFrame.
age_column = df['age']
print(age_column)





# Question 3: Slicing Rows

# 8. Select specific rows using slicing.
selected_rows = df.iloc[2:6]


print(selected_rows)

student_id                        object
age                                int64
gender                            object
study_hours_per_day              float64
social_media_hours               float64
netflix_hours                    float64
part_time_job                     object
attendance_percentage            float64
sleep_hours                      float64
diet_quality                      object
exercise_frequency                 int64
parental_education_level          object
internet_quality                  object
mental_health_rating               int64
extracurricular_participation     object
exam_score                       float64
dtype: object
0      23
1      20
2      21
3      23
4      19
       ..
995    21
996    17
997    20
998    24
999    19
Name: age, Length: 1000, dtype: int64
  student_id  age  gender  study_hours_per_day  social_media_hours  \
2      S1002   21    Male                  1.4                 3.1
3      S1003   23  Female                  1.0                 3.9
4      S1004   19  Female                  5.0                 4.4
5      S1005   24    Male                  7.2                 1.3

   netflix_hours part_time_job  attendance_percentage  sleep_hours  \
2            1.3            No                   94.8          8.0
3            1.0            No                   71.0          9.2
4            0.5            No                   90.9          4.9
5            0.0            No                   82.9          7.4

  diet_quality  exercise_frequency parental_education_level internet_quality  \
2         Poor                   1              High School             Poor
3         Poor                   4                   Master             Good
4         Fair                   3                   Master             Good
5         Fair                   1                   Master          Average

   mental_health_rating extracurricular_participation  exam_score
2                     1                            No        34.3
3                     1                           Yes        26.8
4                     1                            No        66.4
5                     4                            No       100.0

In [ ]:
# Data Cleaning & Manipulation
# Objective: Practice cleaning data and manipulating DataFrames.

# Question 1: Handling Missing Values
# 9. Use the fillna() method to fill missing values with a specific value.
df_filled = df.fillna(0)
df['age'] = df['age'].fillna(0)

In [23]:



# QUestion 2: Renaming Columns
# 10. Change the names of specific columns using rename().
df.rename(columns={'age': 'Student Age'}, inplace=True)

print(df.head())



# Question 3: Dropping Duplicates
# 11. Remove duplicate rows from the DataFrame.
df_no_duplicates = df.drop_duplicates()
print(df_no_duplicates)

  student_id  Student age  gender  study_hours_per_day  social_media_hours  \
0      S1000           23  Female                  0.0                 1.2
1      S1001           20  Female                  6.9                 2.8
2      S1002           21    Male                  1.4                 3.1
3      S1003           23  Female                  1.0                 3.9
4      S1004           19  Female                  5.0                 4.4

   netflix_hours part_time_job  attendance_percentage  sleep_hours  \
0            1.1            No                   85.0          8.0
1            2.3            No                   97.3          4.6
2            1.3            No                   94.8          8.0
3            1.0            No                   71.0          9.2
4            0.5            No                   90.9          4.9

  diet_quality  exercise_frequency parental_education_level internet_quality  \
0         Fair                   6                   Master          Average
1         Good                   6              High School          Average
2         Poor                   1              High School             Poor
3         Poor                   4                   Master             Good
4         Fair                   3                   Master             Good

   mental_health_rating extracurricular_participation  exam_score
0                     8                           Yes        56.2
1                     8                            No       100.0
2                     1                            No        34.3
3                     1                           Yes        26.8
4                     1                            No        66.4
    student_id  Student age  gender  study_hours_per_day  social_media_hours  \
0        S1000           23  Female                  0.0                 1.2
1        S1001           20  Female                  6.9                 2.8
2        S1002           21    Male                  1.4                 3.1
3        S1003           23  Female                  1.0                 3.9
4        S1004           19  Female                  5.0                 4.4
..         ...          ...     ...                  ...                 ...
995      S1995           21  Female                  2.6                 0.5
996      S1996           17  Female                  2.9                 1.0
997      S1997           20    Male                  3.0                 2.6
998      S1998           24    Male                  5.4                 4.1
999      S1999           19  Female                  4.3                 2.9

     netflix_hours part_time_job  attendance_percentage  sleep_hours  \
0              1.1            No                   85.0          8.0
1              2.3            No                   97.3          4.6
2              1.3            No                   94.8          8.0
3              1.0            No                   71.0          9.2
4              0.5            No                   90.9          4.9
..             ...           ...                    ...          ...
995            1.6            No                   77.0          7.5
996            2.4           Yes                   86.0          6.8
997            1.3            No                   61.9          6.5
998            1.1           Yes                  100.0          7.6
999            1.9            No                   89.4          7.1

    diet_quality  exercise_frequency parental_education_level  \
0           Fair                   6                   Master
1           Good                   6              High School
2           Poor                   1              High School
3           Poor                   4                   Master
4           Fair                   3                   Master
..           ...                 ...                      ...
995         Fair                   2              High School
996         Poor                   1              High School
997         Good                   5                 Bachelor
998         Fair                   0                 Bachelor
999         Good                   2                 Bachelor

    internet_quality  mental_health_rating extracurricular_participation  \
0            Average                     8                           Yes
1            Average                     8                            No
2               Poor                     1                            No
3               Good                     1                           Yes
4               Good                     1                            No
..               ...                   ...                           ...
995             Good                     6                           Yes
996          Average                     6                           Yes
997             Good                     9                           Yes
998          Average                     1                            No
999          Average                     8                            No

     exam_score
0          56.2
1         100.0
2          34.3
3          26.8
4          66.4
..          ...
995        76.1
996        65.9
997        64.4
998        69.7
999        74.9

[1000 rows x 16 columns]

In [28]:
# Data Aggregation & Exporting
# Objective: Aggregate data and export the results.

# Question 1: Grouping and Aggregating Data
# 12. Group data by a specific column and calculate the mean for each group.

grouped_means = df.groupby('gender').mean(numeric_only=True)
print(grouped_means)



# Question 2: Exporting Data to CSV
# 13. Export the DataFrame to a new CSV file.
df.to_csv('/workspaces/AI_DATA_ANALYSIS_/src/output_file.csv', index=False)





# Question 3: Aggregating with Multiple Functions
# 14. Apply several aggregate functions to the grouped data.

grouped_stats = df.groupby('gender').agg({
        'exam_score': ['mean', 'max', 'min'],
            'Student age': ['mean', 'count']
            })

         
print(grouped_stats)

        Student age  study_hours_per_day  social_media_hours  netflix_hours  \
gender
Female    20.422037             3.583784            2.503950       1.797921
Male      20.559748             3.510692            2.499371       1.820755
Other     20.666667             3.611905            2.592857       2.057143

        attendance_percentage  sleep_hours  exercise_frequency  \
gender
Female              84.371518     6.471726            2.906445
Male                83.894549     6.438994            3.186583
Other               84.078571     6.804762            2.952381

        mental_health_rating  exam_score
gender
Female              5.453222   69.741372
Male                5.419287   69.368344
Other               5.476190   70.647619
       exam_score              Student age
             mean    max   min        mean count
gender
Female  69.741372  100.0  18.4   20.422037   481
Male    69.368344  100.0  23.1   20.559748   477
Other   70.647619  100.0  43.9   20.666667    42